"""Command-line deployment for the AxonLLM Ledger Amazon Quick dashboard."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Mapping
from dataclasses import asdict
from pathlib import Path
from typing import Any

from axonllm_ledger.quick_dashboard_deploy import (
    QuickDashboardDeployer,
    QuickDashboardDeploymentConfig,
)


def main() -> int:
    """Deploy the dashboard and return a process exit code."""
    parser = argparse.ArgumentParser(
        description=(
            "Deploy the AxonLLM Ledger Amazon Quick dashboard and its "
            "private S3/SPICE data layer."
        )
    )
    parser.add_argument(
        "--dataset-json",
        default="build/quick_dataset.json",
        help="Quick table JSON generated by examples/run_sample_pipeline.py",
    )
    parser.add_argument("--region", default="us-east-1")
    parser.add_argument("--profile")
    parser.add_argument("--aws-account-id")
    parser.add_argument("--principal-arn")
    parser.add_argument(
        "--quick-role-arn",
        help=(
            "Existing account-wide Quick service or S3 consumer role. "
            "Discovered automatically when omitted."
        ),
    )
    parser.add_argument("--bucket")
    parser.add_argument(
        "--prefix",
        default="axonllm-ledger/dashboard-v1",
    )
    parser.add_argument("--dashboard-id", default="axonllm-ledger")
    parser.add_argument("--dashboard-name", default="AxonLLM Ledger")
    args = parser.parse_args()

    try:
        import boto3
        from botocore.config import Config
        from botocore.exceptions import BotoCoreError, ClientError
    except ImportError:
        print(
            'Install the Quick integration with: pip install "axonllm-ledger[quick]"',
            file=sys.stderr,
        )
        return 2

    try:
        tables = _load_tables(Path(args.dataset_json))
        session_kwargs: dict[str, str] = {"region_name": args.region}
        if args.profile:
            session_kwargs["profile_name"] = args.profile
        session = boto3.Session(**session_kwargs)
        client_config = Config(
            retries={"mode": "standard", "total_max_attempts": 4},
            connect_timeout=5,
            read_timeout=90,
        )
        account_id = args.aws_account_id or session.client(
            "sts",
            config=client_config,
        ).get_caller_identity()["Account"]
        principal_arn = args.principal_arn or _discover_quick_principal(
            session.client("quicksight", config=client_config),
            account_id,
        )
        quick_role_arn = args.quick_role_arn or _discover_quick_role(
            session.client("iam", config=client_config)
        )
        bucket_name = args.bucket or (
            f"axonllm-ledger-dashboard-{account_id}-{args.region}"
        )

        config = QuickDashboardDeploymentConfig(
            aws_account_id=account_id,
            region_name=args.region,
            principal_arn=principal_arn,
            bucket_name=bucket_name,
            quick_role_arn=quick_role_arn,
            prefix=args.prefix,
            dashboard_id=args.dashboard_id,
            dashboard_name=args.dashboard_name,
        )
        deployer = QuickDashboardDeployer.from_boto3(
            region_name=args.region,
            profile_name=args.profile,
        )
        result = deployer.deploy(tables, config)
        print(json.dumps(asdict(result), indent=2, sort_keys=True))
        return 0
    except (BotoCoreError, ClientError, OSError, ValueError, RuntimeError) as exc:
        print(f"Dashboard deployment failed: {exc}", file=sys.stderr)
        return 1


def _load_tables(path: Path) -> Mapping[str, list[dict[str, Any]]]:
    if not path.is_file():
        raise FileNotFoundError(
            f"{path} does not exist; run examples/run_sample_pipeline.py first"
        )
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("dataset JSON must contain an object of Quick tables")
    return data


def _discover_quick_principal(
    quick_client: Any,
    aws_account_id: str,
) -> str:
    paginator = quick_client.get_paginator("list_users")
    users = [
        user
        for page in paginator.paginate(
            AwsAccountId=aws_account_id,
            Namespace="default",
        )
        for user in page.get("UserList", [])
        if user.get("Active")
        and user.get("Role") in {"ADMIN", "ADMIN_PRO", "AUTHOR", "AUTHOR_PRO"}
    ]
    if len(users) != 1:
        raise RuntimeError(
            "provide --principal-arn because the default Quick namespace "
            f"contains {len(users)} active author or admin users"
        )
    return users[0]["Arn"]


def _discover_quick_role(iam_client: Any) -> str:
    pattern = re.compile(
        r"^aws-quicksight-(s3-consumers|service)-role-v([0-9]+)$"
    )
    candidates: list[tuple[int, int, str]] = []
    paginator = iam_client.get_paginator("list_roles")
    for role in paginator.paginate().search("Roles[]"):
        match = pattern.fullmatch(role.get("RoleName", ""))
        if match:
            role_type_priority = 1 if match.group(1) == "s3-consumers" else 0
            candidates.append(
                (role_type_priority, int(match.group(2)), role["Arn"])
            )
    if not candidates:
        raise RuntimeError(
            "no account-wide Quick service role was found; provide "
            "--quick-role-arn after configuring Quick security permissions"
        )
    return max(candidates)[2]


if __name__ == "__main__":
    sys.exit(main())
